name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    timeout-minutes: 15 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5.0.1
      with:
        go-version: "stable"

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./... -timeout 5m
