name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    timeout-minutes: 15 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3.5.0
      with:
        go-version: 1.16
    
    - name: Fix DNS
      run: sudo sh -c "echo \"185.41.93.212 dziennikustaw.gov.pl\" >> /etc/hosts"

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
